#!/usr/env/bin python3
#-*- coding: UTF-8 -*-

"""
MIT License

Copyright (c) 2024 Hosein Hadipour 

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

pi = [0x5, 0x0, 0x1, 0x4, 0x7, 0xc, 0x3, 0x8, 0xd, 0x6, 0x9, 0x2, 0xf, 0xa, 0xb, 0xe]

def tex_init(options=""):
    tex_content = r"% generated by plotdistinguisher.py" + options + "\n" + \
             r"\documentclass[preview]{standalone}" + "\n" + \
             r"\usepackage{lblock}" + "\n" + \
             r"\usepackage[margin=2.65in]{geometry}" + "\n" + \
             r"%\tikzset{lblockfig/.append style={white}}" + "\n" + \
             r"\begin{document}" + "\n" + \
             r"\begin{figure}[htp!]" + "\n"
    return tex_content

def tikz_mark_input_bits(bits, color="red"):
    tex_content = r"\begin{tikzpicture}[lblockfig]" + "\n" + \
                  r"\foreach \z in {""" + ",".join([str(bit) for bit in bits]) + \
                  r"} { \fill[" + color + r"] (.25*\z,.75) circle[radius=3pt]; }" + "\n" + \
                  r"   \foreach \z[evaluate=\z as \zf using int(4*\z)] in {0,...,15} {" + "\n" + \
                  r"       \draw[gray] (\z,0) node[above] {\tiny\zf};" + "\n" + \
                  r"       \foreach \zb in {0,...,3} { \draw[gray] (\z+.25*\zb,0) -- +(0,-3pt); }" + "\n" + \
                  r"}" + "\n" + \
                  r"\end{tikzpicture}" + "\n"
    return tex_content

def tikz_mark_output_bits(bits, color="blue"):
    tex_content = r"\begin{tikzpicture}[lblockfig]" + "\n" + \
                  r"\foreach \z[evaluate=\z as \zf using int(4*\z)] in {0,...,15} {" + "\n" + \
                  r"\draw[gray] (\z,-3pt) node[below] {\tiny\zf};" + "\n" + \
                  r"\foreach \zb in {0,...,3} { \draw[gray] (\z+.25*\zb,0) -- +(0,-3pt); }" + "\n" + \
                  r"}" + "\n" + \
                  r"\foreach \z in {" + ",".join([str(bit) for bit in bits]) + r"} { \fill[" + color + \
                  r"] (.25*\z,-.75) circle[radius=3pt]; }" + "\n" + \
                  r"\end{tikzpicture}" + "\n"
    return tex_content

def tex_diff_trail(trail, markpattern, direction="->"):
    tex_content = ""
    nrounds  = trail["nrounds"]
    for r in range(nrounds):
        tex_content += r"\lblockroundwokey{%s" + "\n"
        active__input_branches = [n for n in range(16) if trail[f"x_{r}"][n] != "0"]
        active_even_branches = [n for n in active__input_branches if n%2 == 0]
        active_odd_branches = [n for n in active__input_branches if n%2 != 0]
        tex_content += r"\markevenbranches{" + \
                        ",".join([f"{n}/{pi[n]}" for n in active_even_branches])+ \
                       r"}{" + markpattern + r"}{" + direction + r"}" + "\n"
        tex_content += r"\markoddbranchbeforexor{" + \
                        ",".join([f"{n}" for n in active_odd_branches]) + \
                        r"}{" + markpattern + r"}" + "\n"
        active_after_xor = [n for n in range(16) if trail[f"x_{r+1}"][pi[n]] != "0" and n%2 == 1]
        tex_content += r"\markoddbranchafterxor{" + \
                       ",".join([f"{n}/{pi[n]}" for n in active_after_xor]) + \
                       r"}{" + markpattern + r"}{" + direction + r"}" + "\n"
        tex_content += "}\n"
    return tex_content

def tex_diff_lower_trail(trail, upper_crossing_difference, markpattern, direction="->"):
    tex_content = ""
    nrounds  = trail["nrounds"]
    for r in range(nrounds):
        tex_content += r"\lblockroundwokey{%s" + "\n"
        active__input_branches = [n for n in range(16) if trail[f"x_{r}"][n] != "0"]
        active_even_branches = [n for n in active__input_branches if n%2 == 0]
        active_odd_branches = [n for n in active__input_branches if n%2 != 0]
        if r == 0:
            tex_content += r"\markuppercrossingdifferences{" + \
                           ",".join(upper_crossing_difference) + \
                           "}\n"
        tex_content += r"\markevenbranches{" + \
                        ",".join([f"{n}/{pi[n]}" for n in active_even_branches])+ \
                       r"}{" + markpattern + r"}{" + direction + r"}" + "\n"
        tex_content += r"\markoddbranchbeforexor{" + \
                        ",".join([f"{n}" for n in active_odd_branches]) + \
                        r"}{" + markpattern + r"}" + "\n"
        active_after_xor = [n for n in range(16) if trail[f"x_{r+1}"][pi[n]] != "0" and n%2 == 1]
        tex_content += r"\markoddbranchafterxor{" + \
                       ",".join([f"{n}/{pi[n]}" for n in active_after_xor]) + \
                       r"}{" + markpattern + r"}{" + direction + r"}" + "\n"
        if r == nrounds - 1:
            tex_content += r"\markoutputdiff{" + \
                           ",".join([str(i) for i in range(16) if trail[f"x_{nrounds}"][i] != "0"]) + \
                           "}\n"
        tex_content += "}\n"
    return tex_content

def tex_middle(upper_trail, midd_trail, lower_trail, r0, rm, r1):
    tex_content = ""
    for r in range(rm):
        ur = r + r0
        tex_content += r"\lblockroundwokey{%s" + "\n"
        active_branches_upper = [n for n in range(16) if upper_trail[f"x_{ur}"][n] != "0"]
        active_branches_lower = [n for n in range(16) if lower_trail[f"x_{r}"][n] != "0"]
        active_even_branches_upper = [n for n in active_branches_upper if n%2 == 0]
        active_even_branches_lower = [n for n in active_branches_lower if n%2 == 0]
        active_odd_branches_upper = [n for n in active_branches_upper if n%2 != 0]
        active_odd_branches_lower = [n for n in active_branches_lower if n%2 != 0]
        tex_content += r"\markevenbranches{" + \
                       ",".join([f"{n}/{pi[n]}" for n in active_even_branches_upper])+ \
                       r"}{markmidupperpath}{->}" + "\n"
        tex_content += r"\markoddbranchbeforexor{" + \
                        ",".join([f"{n}" for n in active_odd_branches_upper]) + \
                        r"}{markmidupperpath}" + "\n"
        active_after_xor = [n for n in range(16) if upper_trail[f"x_{ur+1}"][pi[n]] != "0" and n%2 == 1]
        tex_content += r"\markoddbranchafterxor{" + \
                       ",".join([f"{n}/{pi[n]}" for n in active_after_xor]) + \
                       r"}{markmidupperpath}{->}" + "\n"

        tex_content += r"\markevenbranches{" + \
                        ",".join([f"{n}/{pi[n]}" for n in active_even_branches_lower])+ \
                       r"}{markmidlowerpath}{<-}" + "\n"
        tex_content += r"\markoddbranchbeforexor{" + \
                        ",".join([f"{n}" for n in active_odd_branches_lower]) + \
                        r"}{markmidlowerpath}" + "\n"
        active_after_xor = [n for n in range(16) if lower_trail[f"x_{r+1}"][pi[n]] != "0" and n%2 == 1]
        tex_content += r"\markoddbranchafterxor{" + \
                       ",".join([f"{n}/{pi[n]}" for n in active_after_xor]) + \
                       r"}{markmidlowerpath}{<-}" + "\n"
        tex_content += r"\markcommonactivesboxes{" + \
                       ",".join([str(i//2) for i in range(16) if midd_trail[f"s_{r}"][i] == "1"]) + \
                       "}\n"
        if r1 == 0 and r == rm - 1:
            tex_content += r"""	\foreach \z in {""" + \
            ",".join([str(i) for i in range(16) if lower_trail[f"x_{rm + r1}"][i] != "0"]) + \
            r"""} {""" + "\n" + \
            r"""\node[blue,fill,fill opacity=.2, below] at (\z,-6.6) {\phantom{$X_{\!00}$}};""" + \
	         "}\n" + \
            r"""	\foreach \z in {""" + \
            ",".join([str(i) for i in range(16) if upper_trail[f"x_{r0 + rm}"][i] != "0"]) + \
            r"""} {""" + "\n" + \
            r"""\node[red,fill,fill opacity=.2, below] at (\z,-6.6) {\phantom{$X_{\!00}$}};""" + \
	         "}\n" + \
            r"""\foreach \z in {0, ..., 15} {""" + \
            r"""\draw (\z,-6.6) node[below] {$X_{\!\z}$};""" + "\n" + \
            "}"
        tex_content += "}\n"
    return tex_content

def tex_fin(rounds):
    tex_content = r"\caption{Boomerang distinguisher for " + str(rounds) + r" rounds of \texttt{lblock}.}" + "\n" + \
             r"\label{fig:boomerang_distinguisher}" + "\n" + \
             r"\end{figure}" + "\n" + \
             r"\end{document}" + "\n"
    return tex_content
